### ISSUE TITLE
Option to receive both raw and highlighted code

### ISSUE THREAD

**Issue by davidtheclark** [bebraw/highlight-loader#13]
I'd love to get both raw and highlighted code from the input file.

Right now my workaround is to `require` it twice: once with the raw-loader, once with the highlight-loader.

I'd love it if I could set an option on this loader to export an object instead of a string — an object with `raw` and `highlighted` properties.

What do you think? (Happy to work on a PR if you like the idea.)

**Comment by bebraw** [comment]
It's better to handle that using a separate loader to handle the branching. There might be something on npm already. I'm not too keen on adding the feature here (flag is most often a design smell).
