### ISSUE TITLE
Not working with markdown-loader >= 3.0.0

### ISSUE THREAD

**Issue by ljqx** [bebraw/highlight-loader#17]
Since [`markdown-loader` 3.0.0](https://github.com/peerigon/markdown-loader/blob/master/CHANGELOG.md), as it follows [`marked` 0.4.0](https://github.com/markedjs/marked/releases/tag/0.4.0), language prefix is changed from `lang` to `language`, but this loader only accepts `lang`.

**Comment by ljqx** [comment]
sorry, seen the fix. Will close this one. 
BTW, when will it be released?

**Comment by bebraw** [comment]
0.7.3 contains the fix.
