### ISSUE TITLE
NodeJS compat: this.cacheable() not found

### ISSUE THREAD

**Issue by jacargentina** [bebraw/highlight-loader#3]
I'm trying to use this module server-side on my NodeJS app.

```
this.cacheable()
```

is not there.

**Comment by bebraw** [comment]
Thanks for the report. What if we did a check like

``` javascript
this.cacheable && this.cacheable()
```

Can you try that out? I'm not exactly sure what the right solution is but if that works, I can add it in.

**Comment by jacargentina** [comment]
Yes, works fine!

**Comment by bebraw** [comment]
You can find the fix at `0.4.4`. Thanks for the report!
