### ISSUE TITLE
Highlight raw files

### ISSUE THREAD

**Issue by davidtheclark** [bebraw/highlight-loader#5]
I would like to be able to use this in combination with raw-loader to highlight raw files that do not contain the `<code>` tag (or any HTML).

For example, I'd like to:

``` js
var myCodeHighlighted = require('!!raw!highlight!myCode.js');
```

Any interest in adding this feature? If so, I could work on a PR for it.

**Comment by bebraw** [comment]
Sure, PR is welcome!

Btw, the approach the loader uses internally (cheerio -> highlight) isn't particularly performant. Often it's better to solve that through Markdown parser hook. At least the current implementation doesn't tie the loader to some particular environment.

**Comment by davidtheclark** [comment]
Done in #7.
